name: CodSpeed

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'
      - '.gitignore'
  push:
    branches:
      - master
  workflow_dispatch:

env:
  UV_VERSION: 0.11.11

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: rustup install --profile minimal
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          version: ${{ env.UV_VERSION }}
      - run: uv sync --frozen --config-setting build-args=--profile=benchmark
      - uses: CodSpeedHQ/action@f99becdce5e5d51fd556489ebef684f4ecfd6286 # v4.18.5
        with:
          mode: simulation
          run: uv run --no-sync pytest --codspeed benchmarks
