name: CodSpeed

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/dependabot.yml'
      - '.gitignore'
  push:
    branches:
      - master
  workflow_dispatch:

env:
  UV_VERSION: 0.11.11

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: rustup install --profile minimal
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: ${{ env.UV_VERSION }}
      - run: uv sync --frozen --config-setting build-args=--profile=benchmark
      - uses: CodSpeedHQ/action@4296e51e7041e24dadb86d1d6e8b9320d223dbe8 # v5.0.3
        with:
          mode: simulation
          run: uv run --no-sync pytest --codspeed benchmarks
